language: shell
before_install:
- eval $(./deploy.sh vars)
env:
  global:
  - secure: "MkhpuHqJwplF5zqj5voNMW6ZV7o57zY+FV53cp/XBCLclwYxb+RUjmY7VbIuxGy+CyscsqADZAkCCVR5v0FIjM7WbMht+n5CbBnfgkR2hg+wv1CJuPsfgeCrpgg3WLI5Xbmv6tWZRxRUXRsLFQ6OgvYgT5b5Z0VfnhNv3Sd0JXuVr9Gld+Y9EKOQsvubSDT5Zpf4grHyUz7KFhK2R2mvM/TATR4JOFd6byEix8C9Y4YW9udyiDAmXP69lCyX/hQtY/m9p4+McKEarLrbuK6TnRsGp85bnq+dGrElb84ekNLfDuiTfr+MLJ5EMo85PP1IZqpbthoyGPOSjFcZZyMwiZHdx1iF3TpMEv+HUSNF73MqPWi7EQPGsQ7sqmuw5UXsf8VYrBk3rooovOrwU9gSR7oKR+SwVPywFcVQ46qU2J4w3kWQvfxb/LnRZZZ3cWN+8gpN4oMgHtNLA7Kz1klbyDTukqc0I/Bv/DsWLgjk5SCAngq3id/a5AKDttRb8wCXDKYbMWI8LpzG9B5c2T18d4q+xnOcEL5oHQ0WtdA0YRJm4Y2bs+ugMglNYVCpc9knDrSRNa+kDrovABWnZGuOZ1R52sxxv7kjLDCNq5s0EpAYIhQpJ5UP9S+DJ1rK5kixkmigP5NRZjhLEyhHEkhs2zjSbeC88Y+Mn+RYWLcsirw="
script: make verify
after_success:
- make check
deploy:
- provider: script
  skip_cleanup: true
  script: ./deploy.sh check
  on:
    condition: $CHANGED = 1