language: shell
env:
  global:
  - secure: "rhX4sCsYXAi4o/HfZ4b7v//aC0c/ShKXpxkJHuSrP8iZ/vjhtMW1jU9TBH8HNhqMmpw+kWiQRHRCCA2C9NPe2Mv1+j4Z44IJKU0Ux8OIqJYVqOcJcRXiKCghPxM9nfYm4iz4oTGFOXte9v6PXFpztpOp7D9ax5+PDSFoWBCPAaWQkKVMMVP4TlGAWdWE4i+KztxvSQSIshAfOm/2PT/jgUlFX9//rSldmT4Q6tUGR1ZXkiEIgz9ZkY2c1swi+OQSvbGojW4X7QlugPxAf5y/NGFwXRjgKFzTk5MWBxEJy8HCziD57OD/KyHoQjWSO1YZ5f9fiHmqgfHeBreQme/d8YrWRIMzytYlB+YuwVJgsJt+rGvgzruBpzSlxqsH/Ly0YXCGpL6WFC3j9ZOCTcPIFMJn9rDF//1pUoAlH2lYEf6CAiqRZrcq8zt1u0ggiS71sRDrB6SM2uml00t/afXs4wfY4gNuxrAXaBdxuno+0okbiuTyd0POBiRmZvMOnm4F8OxzrxcB8Z4xzK/wDqgftcjm2LTNcmI1zOZNmJQvgmmU7fbcfTLX9HX0nOXetyCndbUQcC5iIeVof66W5ctDJMvDSSEMhpuf1OKCouTdn/kjEJjyPYBjIrcyBOKuw2twjBgxXx8dR/7D8p66t+/CtevyWsz/RYGyK+4M9imoslo="
script: make push
after_success:
- make check
