# This file was generated by GoReleaser. DO NOT EDIT.
class Kafkactl < Formula
  desc "CLI for Apache Kafka and Zookeeper Management."
  homepage "http://www.jbvm.io/kafkactl"
  version "1.0.25"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/jbvmio/kafkactl/releases/download/v1.0.25/kafkactl_1.0.25_Darwin_x86_64.tar.gz"
    sha256 "26d7bf9cd509ab21a6e3f2e621f57bb86f779311c51c44fb1f0dbabf1819c422"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/jbvmio/kafkactl/releases/download/v1.0.25/kafkactl_1.0.25_Linux_x86_64.tar.gz"
      sha256 "3db51f3ff62886ad71dbe750e50b57964c12020bf83fc61d7f91a784a6813484"
    end
  end

  def install
    bin.install "kafkactl"
  end

  test do
    system "#{bin}/kafkactl version"
  end
end
