# This file was generated by GoReleaser. DO NOT EDIT.
class Kafkactl < Formula
  desc "CLI for Apache Kafka and Zookeeper Management."
  homepage "http://www.jbvm.io/kafkactl"
  url "https://github.com/jbvmio/kafkactl/releases/download/v1.0.22/kafkactl_1.0.22_Darwin_x86_64.tar.gz"
  version "1.0.22"
  sha256 "b30a82a5084119156d681d0433536c1166955faa27f0a0b94b621d187745c051"

  devel do
    url "https://github.com/jbvmio/kafkactl/releases/download/v1.0.22-beta.12856731/kafkactl_1.0.22-beta.12856731_Darwin_x86_64.tar.gz"
    version "1.0.22-beta.12856731"
    sha256 "afc1397dd641f9b613966def0c65fe168c3b8afc13a295c570bc3b6d5a24791c"
  end

  def install
    bin.install "kafkactl"
  end
  test do
    system "#{bin}/kafkactl version"
  end

