# This file was generated by GoReleaser. DO NOT EDIT.
class KafkactlATLatest < Formula
  desc "CLI for Apache Kafka and Zookeeper Management."
  homepage "http://www.jbvm.io/kafkactl"
  url "https://github.com/jbvmio/kafkactl/releases/download/v1.0.21/kafkactl_1.0.21_Darwin_x86_64.tar.gz"
  version "1.0.21"
  sha256 "59edf7d44672c1a3d48047a0d2437c9102345239d8851ca9ba76b457f27bacf0"

  def install
    bin.install "kafkactl"
  end

  test do
    system "#{bin}/kafkactl version"
  end
end
