# This file was generated by GoReleaser. DO NOT EDIT.
class Kafkactl < Formula
  desc "CLI for Apache Kafka and Zookeeper Management."
  homepage "http://www.jbvm.io/kafkactl"
  url "https://github.com/jbvmio/kafkactl/releases/download/v1.0.21-beta.5439615/kafkactl_1.0.21-beta.5439615_Darwin_x86_64.tar.gz"
  version "1.0.21-beta.5439615"
  sha256 "3dbae871902dd48b3504c6b790a60d397ae0a3ddc3974e1b50bb9bdfb2c264e1"
  
  devel do
    url "https://github.com/jbvmio/kafkactl/releases/download/v1.0.21-beta.5439615/kafkactl_1.0.21-beta.5439615_Darwin_x86_64.tar.gz"
    version "1.0.21-beta.5439615"
    sha256 "3dbae871902dd48b3504c6b790a60d397ae0a3ddc3974e1b50bb9bdfb2c264e1"
  end

  def install
    bin.install "kafkactl"
  end

  test do
    system "#{bin}/kafkactl version"
  end
end
